### ISSUE TITLE
No comunication error??

### ISSUE THREAD

**Issue by multilectical** [croutonso/PZEM017modbus#3]
Hi, I've been trying to get this working on a rock64 SBC (running Armbian 23.11.1 bookworm) and keep getting this message:

```
onion@karakung:~/PEMZ/PZEM017modbus$ ../bin/python3 pzem_reader.py 
Traceback (most recent call last):
  File "/home/onion/PEMZ/PZEM017modbus/pzem_reader.py", line 52, in <module>
    read_pzem_data()
  File "/home/onion/PEMZ/PZEM017modbus/pzem_reader.py", line 22, in read_pzem_data
    voltage = instrument.read_register(0x0000, number_of_decimals=2, functioncode=4)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onion/PEMZ/lib/python3.11/site-packages/minimalmodbus.py", line 484, in read_register
    returnvalue = self._generic_command(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onion/PEMZ/lib/python3.11/site-packages/minimalmodbus.py", line 1276, in _generic_command
    payload_from_slave = self._perform_command(functioncode, payload_to_slave)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onion/PEMZ/lib/python3.11/site-packages/minimalmodbus.py", line 1353, in _perform_command
    response_bytes = self._communicate(request_bytes, number_of_bytes_to_read)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onion/PEMZ/lib/python3.11/site-packages/minimalmodbus.py", line 1521, in _communicate
    raise NoResponseError("No communication with the instrument (no answer)")
minimalmodbus.NoResponseError: No communication with the instrument (no answer)
```

I see the device on /dev/ttyUSB0, but can't figure out why it doesn't see it. I'm thinking the DEVICE_ADDRESS setting may be wrong but can't see where to find the correct setting there.

here's the settings from my pzem_reader.py:

```
DEVICE_ADDRESS = 0x01
BAUD_RATE = 9600
TIMEOUT = 1
PORT = '/dev/ttyUSB0'
```
any ideas?

**Comment by shakidc** [comment]
I got the same problem here, I try to change the slave address within 0x01 - 0xF7 (based on the datasheet) but still got the same error. I've checked the wiring and it's just fine. I'm using Raspberry Pi 3B+ and RS485 to USB converter here. I've read that this kind of error can be happened if the device is offline, but do you have any way to check whether the PZEM-017 is on or not? Because there wasn't any indicator on it.

**Comment by shakidc** [comment]
> Hi, I've been trying to get this working on a rock64 SBC (running Armbian 23.11.1 bookworm) and keep getting this message:
> 
> ```
> onion@karakung:~/PEMZ/PZEM017modbus$ ../bin/python3 pzem_reader.py 
> Traceback (most recent call last):
>   File "/home/onion/PEMZ/PZEM017modbus/pzem_reader.py", line 52, in <module>
>     read_pzem_data()
>   File "/home/onion/PEMZ/PZEM017modbus/pzem_reader.py", line 22, in read_pzem_data
>     voltage = instrument.read_register(0x0000, number_of_decimals=2, functioncode=4)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/onion/PEMZ/lib/python3.11/site-packages/minimalmodbus.py", line 484, in read_register
>     returnvalue = self._generic_command(
>                   ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/onion/PEMZ/lib/python3.11/site-packages/minimalmodbus.py", line 1276, in _generic_command
>     payload_from_slave = self._perform_command(functioncode, payload_to_slave)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/onion/PEMZ/lib/python3.11/site-packages/minimalmodbus.py", line 1353, in _perform_command
>     response_bytes = self._communicate(request_bytes, number_of_bytes_to_read)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/onion/PEMZ/lib/python3.11/site-packages/minimalmodbus.py", line 1521, in _communicate
>     raise NoResponseError("No communication with the instrument (no answer)")
> minimalmodbus.NoResponseError: No communication with the instrument (no answer)
> ```
> 
> I see the device on /dev/ttyUSB0, but can't figure out why it doesn't see it. I'm thinking the DEVICE_ADDRESS setting may be wrong but can't see where to find the correct setting there.
> 
> here's the settings from my pzem_reader.py:
> 
> ```
> DEVICE_ADDRESS = 0x01
> BAUD_RATE = 9600
> TIMEOUT = 1
> PORT = '/dev/ttyUSB0'
> ```
> 
> any ideas?

I've solved this error by change the RS485 to USB connector from this one:

![image](https://github.com/croutonso/PZEM017modbus/assets/43099721/0ade6d8a-5e60-4127-9390-fd196bb3b3ce)

to this one:

![image](https://github.com/croutonso/PZEM017modbus/assets/43099721/f2794f55-d5e1-406b-b49b-d3df504e7043)

It worked just fine after I changed the connector. Turn out for some reason (Idk what the specific case), this sensor only work with this kind of connector (I've tried the other one on every machine and OS that I have but it still didn't work). Hope my answer can help you with it.

**Comment by multilectical** [comment]
hmm, interesting and glad you got that sorted. though I did have the 2nd one all along. I'll try using different converters/cables and see what happens.

**Comment by KevinNelSL** [comment]
@multilectical did you fix it?

**Comment by multilectical** [comment]
@KevinNelSL  nope. Couldn't get this working.

I ended up up choosing another path (via home assistant/esphome), but I did have the peacefair Rs485 to USB connector in the pic above and same thing happened for me. I also tried with several different boards (orange pi, rock64, raspberry). I'm sure I was just missing something basic. The hardware stuff is not my superpower.

**Comment by KevinNelSL** [comment]
Yeah I was fighting this the whole day. I tried just using modbus RTU directly,  tried multiple computers, wiring powering the device woth different supplies. I was probing the data lines with a scope and couldn't get this peacefair thing to respond. Possible that the device is just a dud because it seems many people have it working online. I don't think this is an issue with this repo.

**Comment by trisax** [comment]
Hi everybody
I got the sane error.
Changed my PZEM 017 (return to seller),
tried to deactivate UART in config.txt, cmdlines.txt, ...

I had to install using venv. 
My SETUP : 

> Raspberry Pi 3 Model B Plus Rev 1.3
> Raspbian GNU/Linux 12 (bookworm)

My code lines to install :


```
python3 -m venv pzem-env		#créer environnement virtuel 
source pzem-env/bin/activate	#Activez l'environnement virtuel 

pip3 install minimalmodbus pyserial
git clone https://github.com/croutonso/PZEM017modbus.git

cd  ~/PZEM017modbus
sudo nano ~/PZEM017modbus/pzem_reader.py 
	DEVICE_ADDRESS
	PORT
	...any other parameters according to your device and connection.
	
python3 ~/PZEM017modbus/pzem_reader.py
```

I only get connection error return 

> thierry@Voltro:~ $ source pzem-env/bin/activate
> (pzem-env) thierry@Voltro:~ $ python3 ~/PZEM017modbus/pzem_reader.py
> Traceback (most recent call last):
>   File "/home/thierry/PZEM017modbus/pzem_reader.py", line 52, in <module>
>     read_pzem_data()
>   File "/home/thierry/PZEM017modbus/pzem_reader.py", line 23, in read_pzem_data
>     current = instrument.read_register(0x0001, number_of_decimals=2, functioncode=4)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/thierry/pzem-env/lib/python3.11/site-packages/minimalmodbus.py", line 484, in read_register
>     returnvalue = self._generic_command(
>                   ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/thierry/pzem-env/lib/python3.11/site-packages/minimalmodbus.py", line 1276, in _generic_command
>     payload_from_slave = self._perform_command(functioncode, payload_to_slave)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/thierry/pzem-env/lib/python3.11/site-packages/minimalmodbus.py", line 1353, in _perform_command
>     response_bytes = self._communicate(request_bytes, number_of_bytes_to_read)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/thierry/pzem-env/lib/python3.11/site-packages/minimalmodbus.py", line 1521, in _communicate
>     raise NoResponseError("No communication with the instrument (no answer)")
> minimalmodbus.NoResponseError: No communication with the instrument (no answer)
